# Generated by Django 3.1.2 on 2021-05-29 16:24
from django.contrib.auth.models import User
from django.db import migrations


def add_admin(app, scheme_editor):
    user = User(
        id=1,
        username='admin',
        is_active=True,
        email='admin@email.com',
        is_staff=True,
        is_superuser=True
    )
    user.set_password('admin')
    user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_admin)
    ]
