# Generated by Django 3.1.2 on 2021-06-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_auto_20210603_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
